apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tf-model-serv.fullname" . }}-gsa
  labels:
    {{- include "tf-model-serv.labels" . | nindent 4 }}
type: Opaque
data:
  GCP_SA_KEY: {{ .Values.gcp.saKey | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tf-model-serv.fullname" . }}-tls
  labels:
    {{- include "tf-model-serv.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}