apiVersion: v1
kind: Service
metadata:
  name: {{ include "tf-model-serv.fullname" . }}
  labels:
    {{- include "tf-model-serv.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    # - port: {{ .Values.service.restPort }}
    #   targetPort: rest
    #   protocol: TCP
    #   name: rest
  selector:
    {{- include "tf-model-serv.selectorLabels" . | nindent 4 }}
